FROM ubuntu:18.04

COPY vc-controller-manager /vc-controller-manager

RUN useradd -d /home/hwMindX -u 9000 -m -s /usr/sbin/nologin hwMindX && \
    chown -R hwMindX:hwMindX vc-controller-manager && \
    chmod 500 vc-controller-manager
USER hwMindX