FROM alpine:latest

COPY vc-scheduler /vc-scheduler
COPY volcano-npu_*.so plugins/
ENV pluginName=volcano-npu-v2.0.3
RUN adduser -h /home/hwMindX -u 9000 -D -s /sbin/nologin hwMindX && \
    chown -R hwMindX:hwMindX plugins vc-scheduler && \
    chmod 500 plugins vc-scheduler && \
    chmod 400 plugins/*.so

USER hwMindX