FROM alpine:latest

COPY vc-controller-manager /vc-controller-manager

RUN adduser -h /home/hwMindX -u 9000 -D -s /sbin/nologin hwMindX && \
    chown -R hwMindX:hwMindX vc-controller-manager && \
    chmod 500 vc-controller-manager
USER hwMindX